### ISSUE TITLE
As a dev I want to see the backend status and current version hash

### ISSUE THREAD

**Issue by r44cx** [ZHAW-PM4-Compass/compass#106]
**Description**

**Estimate**
S - Storypoints 

**Tasks Checklist**
- [x]  FE: Hidden Page for BE Status (call "/"-Endpoint and display 🔴 or🟢) and later commit hash.
- [x]  Research how to pass commit hash during build
- [x]  BE: System Status GET

**Acceptance Criteria**

**Non-Functional Requirements**

**Dependencies**
