### ISSUE TITLE
As a admin I want to create user accounts with role for new users

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#12]
**Description**
The admin should be able in a "/users" endpoint to add new users with roles and display all those in a list.

**Estimate**
L Storypoints

**Tasks Checklist**
- [x] FE: Users table view
- [x] FE: Base components for Table, Title, Button, etc.
- [x] FE: Create  
- [x] BE: Routing backend calls to Auth0
- [x] ADR for new Role handling

**Acceptance Criteria**
- User can be created
- Token of user is persisted in local database
- User is created on auth0

**Dependencies**
Auth0 needs to be set up
Figma Design

**Comment by noahbaumgartner** [comment]
With PR https://github.com/ZHAW-PM4-Compass/compass/pull/88 the user create is on staging and with that this issue is closed.
