### ISSUE TITLE
As a admin I want to delete accounts for security purpose

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#14]
**Description**
It should be possible to delete accounts, so the user is no more possible to log in into the application. Because the user data shouldn't be deleted to hold the references, the user just gets blocked on auth0 and thats all.

**Estimate**
M 

**Tasks Checklist**
- [x] FE: delete button
- [x] FE: revert deletion
- [x] BE: delete action to auth0 with endpoint
- [x] BE: revert action to auth0 with endpoint

**Acceptance Criteria**
- The admin can delete a user
- The admin can restore a deleted user

**Dependencies**
This user story (needs, blocks, has to be done with, depends on etc): 
- Design
