### ISSUE TITLE
As a participant/social worker I want to fill in the daily report of the mood in diffrent predefined categories

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#15]
**Further Details**
Since categories up for a rating are dynamic we define the process as follows:

For the _Social-Worker_: FE passes User ID to receive all categories   
-> BE collects categories as Union of all **global** categories (User is NULL) and User categories
-> FE receives categories array and passes back same array with ratings and DaySheet-ID and User ID
-> BE records ratings to DaySheet and sets ratings type based on flag in input and later role in passed JWT

For the _Participant_: FE doesn't need to pass User ID, token is sufficient.  
FE has to call a different endpoint for _Participant_ or _Social-Worker_ ratings.

See #23 for more details on categories. 

**Estimate**
L - Storypoints 

**Tasks Checklist**
- [x] FE: Implement components for dynamic category list ratings as defined in [Figma design](https://www.figma.com/file/JKptvUrA9Iiv2Nj61yHqum/Compass-UI?type=design&node-id=2-3&mode=design)
- [x] BE: Implement *getCategoryListByUserId()* endpoint
- [x] BE: Implement *recordCategoryRatingsByDaySheetAndUserId()* endpoint
- [x] BE: Implement necessary Rating getter-Endpoint: By Date and Optional Participant with Output: Date, Participant Name, Category-Name, Rating: *getMoodRatingByDate()*
- [x] FE: Implement Category rating input modal
- [x] FE: Implement Category rating view page
- [x] BE: Spring Security Logs should not run in DEBUG mode on Prod
- [x] BE: Define Unit Tests for endpoints/methods
- [x] FE: Define E2E Tests
- [x] Deploy new DEBUG level env variable to PROD
- ~~FE: Hidden Page for BE Status (call "/"-Endpoint and display 🔴 or🟢) and later commit hash.~~
- ~~Deployment: `image:latest` doesn't work when applying K8 deployment~~

**Acceptance Criteria**
- The lifecycle of a rating is fully implemented: input and display
- A reasonable amount of tests are delivered
- The ratings system integrates with time tracking lifecycle

**Non-Functional Requirements**
- The BE implementation is done with foresight to #55 

**Dependencies**
This user story duplicates #18:
We combine both stories and close #18. For now the rating type will be driven by a flag set in the request. When user roles functionality is more mature we will implement the type trigger based on the role passed in the JWT as defined in #55 
 
This user story is to be completed with #57

This user story is linked to and partially blocked by #23:  
The categories a user should provide a rating for are dynamic and are based on Inputs by the admin.

This user story is also dependant on all auth0 user stories.
