### ISSUE TITLE
As a social worker I want to confirm the working time of participants

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#17]
**Description**
As a social worker I want to be able to confirm all the working time of the participants.

**Estimate**
M - Storypoints

**Tasks Checklist**
- [x] Social worker sees all unconfirmed day sheets
- [x] Social worker sees sum of working hours in overview
- [x] Social worker can open the corresponding day sheet
- [x] Social worker can confirm day sheet
- [x] Only social worker can confirm working hours. Participants can not see the corresponding page

**Acceptance Criteria**

- DOD is checked

**Dependencies**
- Auth0 for role
