### ISSUE TITLE
As a social worker I want to fill in the daily report in text form

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#19]
**Description**
As a social worker I want to fill in the daily report in text form.

**Estimate**
 L Storypoints

**Tasks Checklist**
- [x] FE: As a Social Worker I can generate a report on a specific day for any participant
- [x] FE: The text field should have basic functionalities but no specific structure
- [x] FE: The reports can be saved and are accessible for the Social Worker 
- [x] FE: Only the Social Worker has access to the daily reports and can create them
- [x] BE: Change name of field in `daySheet`/`day_sheet`/etc. from `day_report` to `day_notes`
- [ ] FE: testing

**Acceptance Criteria**
- DoD is checked

**Dependencies**
- tbd
