### ISSUE TITLE
As a social worker I want to report the occurrence of special events of the participant

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#20]
**Description**
It should be possible to report the occurrence of special events of a participant. The participant can just report his own special events and the social worker can do this for all participants

**Estimate**
M

**Tasks Checklist**
- [x] FE: List of special events
- [x] FE: Create Popup
- [x] FE: Update Popup
- [x] FE: Delete Function
- [x] BE: Create Special Event
- [x] BE: Update special event
- [x] BE: Delete special Event
- [x] BE: Tests

**Acceptance Criteria**

- The participant is able to manage his own special events
- The social worker is able to manage the special events for all users

**Non-Functional Requirements**
- Figma Design
