### ISSUE TITLE
As a social worker I want to create a view of the mood categories, special events and time traking of participants

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#21]
**Description**
The social worker should have a monthly overview of mood categories, special events and the timetracking of one participant.

**Estimate**
L

**Tasks Checklist**
- [x] BE: get daysheets by month
- [x] FE: graph for incidents
- [x] FE: graph for categories and timetracking
- [x] FE: settings to select month and participants
- [x] FE: settings to select participant or social working categories

**Acceptance Criteria**
- A social worker can view incidents, categories and timetracking in an overview

**Dependencies**
- Figma

**Comment by noahbaumgartner** [comment]
Charts wiht https://mui.com/x/react-charts/axis/. First draft: 
![Screenshot 2024-05-13 at 10  20 21@2x](https://github.com/ZHAW-PM4-Compass/compass/assets/35225015/5d088cb2-0d97-408f-9e44-4df8c6fb56ef)
