### ISSUE TITLE
As a developer I want to have access to a user Spring Boot repository so I can link users to daySheets and other classes

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#57]
**Further Details**
https://auth0.com/docs/quickstart/backend/java-spring-security5/interactive

**Estimate**
M - Storypoints

**Tasks Checklist**
- [x] Implement a user repository that can be easily linked to the dependant classes
- [x] Connect users of the type participant to their timesheets
- [x] Implement a create and update service to add users
- [ ] ~~Solution for User Table consistency for Devs~~ Has to be done ad hoc amongst devs for now

**Acceptance Criteria**
- The user repository has enough Info to link to a user on auth0 and to identify the user in Compass (auth0 ID, first and last name) 
- A reasonable amount of tests are delivered

**Non-Functional Requirements**
- Easily extensible and linked to other classes

**Dependencies**
DaySheets, Categories, Ratings and reports depend on this user story.
