### ISSUE TITLE
As a PM4 student I want to present our project to potential customers (No-Tech document)

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#65]
**Further Details**
As part of the school project we have decided to create a webpage that present our project and its features to potential customers. This counts for 20% of our final grade

**Estimate**
L Storypoints

**Tasks Checklist**
- [x] Set up Website frame work
- [x] Define theme/look
- [x] Deploy a pod for landing page
- [x] Fill content: text
- [x] Fill content: screenshots and pictures
- [x] Get feedback from noTech lecturer
- [x] Submission to moodle before 16.06.

**Acceptance Criteria**

- "No-Tech" lecturer is able to visit website about our project
- Visitor has a full overview of our project and its features
- Presentation looks like a real product

**Dependencies**
This user story depends on the project being mature enough to be able to present concrete features.
