### ISSUE TITLE
As a developer I want to have a fully defined Codecove flow

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#82]
**Further Details**
Codecov reports are now integrated in the PR workflow and are delivering results but some decisions and refinements/configurations are still outstanding. 

**Estimate**
S Storypoints

**Tasks Checklist**
- [x] In the team define which code is excluded from the coverage requirement (reasonably) and implement
- [ ] In the team define what code coverage criteria should be set as gates for PRs and implement
- [x] Set up a label in the project Readme to show the current project coverage %

**Comment by x-snackage-x** [comment]
Team decided to have initially have a target of 70% with a threshold of 5% for both sub components of the application. If the coverage reaches 80% over the coming release than the target will be increased to 80%.

**Comment by r44cx** [comment]
Replace JESTER with Playwright Test Coverage https://github.com/mxschmitt/playwright-test-coverage

**Comment by x-snackage-x** [comment]
Codecov workflow is set and functional but two points remain open:
1. Codecov ignore seems to not ignore set paths
2. Due to point 1 and resulting coverage inflation the PR gate has not been set at the agreed on 80% coverage.
